site_name: FreeODwiki——可自由编辑的开源Overdose百科
site_url: https://freeodwiki.org
site_author: FreeODwiki贡献者们
site_description: FreeODwiki是一个开源项目，旨在让每一位ODer都能有效地获取和分享有关Overdose和精神活性物质的信息，并在减少上述事物对ODer造成的伤害的同时，为上述事物提供一个独特的视角。 # 站点描述
docs_dir: ./docs # 你的 Markdown 文件夹路径（相对或绝对路径）
site_dir: ./site

use_directory_urls: false

repo_name: diyumid/FreeODwiki
repo_url: https://github.com/diyumid/FreeODwiki

extra_css:
  - css/extra.css
  - css/external_link_icon.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - search
  # - optimize
  - awesome-nav:
      logs:
        nav_override: warning
        root_title: warning
        root_hide: warning
        no_matches: warning
  - glightbox
  - document-dates

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    anchors: ignore
    absolute_links: ignore
    unrecognized_links: ignore

markdown_extensions:
  - abbr
  - admonition # 各类提示块
  - attr_list # 属性列表扩展
  - def_list
  - footnotes # 内联脚注
  - md_in_html
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - 药物/*
              - 药效/*
              - 文档/*
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  #  - pymdownx.emoji:
  #      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # 行内语法高亮Z
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: SalviaSWC
      repo: FreeODwiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {} # Unicode 支持
      permalink: true # 各级标题锚点  

theme:
  language: zh
  name: material
  custom_dir: overrides # 自定义覆盖模板文件夹
  favicon: 文件/FreeODwiki2.png
  logo: 文件/FreeODwiki2.png

  features:
    - navigation.top # 上滑时显示「回到页面顶部」按钮
    - navigation.path # 显示路径（二级目录之后显示）
    - navigation.tabs # 导航顶栏（一级目录）
    - navigation.tabs.sticky # 固定导航顶栏，下滑不消失
    - navigation.indexes # 目录索引页，开启后自动绑定 index.md
    - content.tooltips
    - content.footnote.tooltips
    - content.code.copy
    - search.share
    - search.suggest
    - search.highlight

  palette: # 配色
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" # 亮色
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" # 暗色
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
